name: build&enjoy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xpm
      run: sudo apt-get install -y libgd-dev libx11-dev
    - name: make
      run: make
